services:
  axelor:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXUS_READER_USERNAME: ${NEXUS_READER_USERNAME}
        NEXUS_READER_PASSWORD: ${NEXUS_READER_PASSWORD}
        CATALINA_MEMORY_ALLOC_PCT: "25"
    environment:
      PGHOST: postgres
      PGUSER: axelor
      PGPASSWORD: axelor
      PGDATABASE: axelor
      APP_DEMO_DATA: "true"
      DEV_MODE: "true"
    ports:
      - "8080:8080"
  postgres:
    image: "postgres:16"
    environment:
      POSTGRES_USER: axelor
      POSTGRES_PASSWORD: axelor
      POSTGRES_DB: axelor